# -*- coding: utf-8 -*-
"""Opencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkWBuGymCVc63HTj3KZP7YGxbZDbopzR
"""

# --- Leitura e modificação de imagem estatica ---
import cv2
from google.colab.patches import cv2_imshow

# 1. Carregar a imagem

imagem = cv2.imread('cenario.jpg')

# 2. Redimenciona para um tamanho padrão

imagem = cv2.resize(imagem, (680,480))

# 3. Converter para escala de cinza(simplificação matemática da matriz)

imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

# 4. Desenhar uma caixa de arcação manual em uma area da imagem
# Parâmetros: cv2.rectangle(imagem, (x_inicio, y_inicio),(x_fim, y_fim), (B,G,R), espessura)

cv2.rectangle(imagem, (150,100), (500,400), (255,0,0),3)
cv2.putText(imagem, "REGIÃO DE INTERESSE",(150,90), cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,0,0),2)

# 5. Exibir os resultados na tela
print("---imagem Original com marcação")
cv2_imshow(imagem)

print("\n---Imagem em escala de cinza")
cv2_imshow(imagem_cinza)

# instalar s bibliotecas
!pip install easyocr opencv-python

# Leitura automatica de placas (openCV + OCR)
import cv2
import easyocr
from google.colab.patches import cv2_imshow

# 1. inicializado o leitor de OCR da IA para o idioma Portugguês
leitor_ocr = easyocr.Reader(['pt'])

# 2. Carregar a imagem do veículo e redimencionar para manter um padrão

imagem_veiculo = cv2.imread('carro.jpg')
imagem_veiculo = cv2.resize(imagem_veiculo,(800,600))

# 3. Converter para escala de cinza para facilitar a leitura de caracters pela IA

imagem_cinza = cv2.cvtColor(imagem_veiculo, cv2.COLOR_BGR2GRAY)

# 4. Deefinir a região de interesse (ROI) da placa
#  Formato do recorte de matrizes no python: imagem[y_inicio:y_fim,x_inicio:x_fim]

# exemplos coodernadas

x_ini, x_fim = 170,280
y_ini, y_fim = 410,450

placa_recortada_cinza = imagem_cinza[y_ini:y_fim,x_ini:x_fim]
placa_recortada_colorida = imagem_veiculo[y_ini:y_fim,x_ini:x_fim]

# 5. Passar o recorte da IA de OCR para extrair as letras/números

print("[SISTEMA] Escaneando caracteres da placa...")
resultados_ocr =  leitor_ocr.readtext(placa_recortada_cinza)

# 6. Extrair o texto encontrado se a IA conseguir ler algo

if len(resultados_ocr) >0:
    # o resultado do EasyOCR vem no formato: [(cordenadas), "TEXTO DETECTADO",score_confiaça]
    texto_placa = resultados_ocr[0][1].upper().replace(" "," ")
    confianca = resultados_ocr[0][2]*100

    #7 Usar o opencv para desenhar o rsultado e volta na imagem
    cv2.rectangle(imagem_veiculo,(x_ini,y_ini),(x_fim,y_fim),(0,255,0),3)
    cv2.putText(imagem_veiculo, f"PLACA: {texto_placa} ({confianca:.1f}%)",(x_ini,y_ini - 15), cv2.FONT_HERSHEY_SIMPLEX,0.7,(0,255,0),2)

    print(f"\n [SUCESSO] Texto extraído pela IA: {texto_placa}")
else:
    print("\n[ALERTA] Não foi possível identificar os caracteres. Ajuste o recorte da ROI")
    texto_placa = "NÃO DETECTADA"

# 8. Exibir o painel visual final para validação
print("\n--- Recorte focado em enviado para IA")
cv2_imshow(placa_recortada_colorida)

print("\n--- resultado do sistema de monitoramento---")
cv2_imshow(imagem_veiculo)

